---
title: "Weinstein_PollinatorInteractions"
author: "Sarah Weinstein"
date: "2024-11-13"
output: html_document
---
 how do i fix this 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## LP: I know you all changed this considerably. Can you plese resubmit a new version by Friday or Monday next week? The focus should be on te OBA data.

-Literature Review

Upon talking with the professor and discussing this with my partner further we have shifted our focus to look at different forested areas that bees have been found using the oregon bee atlas dataset and create interaction webs and compare those webs to each other to determine which common plants appear across the different areas. We plan to use this data to identify common native plants that bees routinely visit in different areas and see how that can be imlimented into agriculture. As part of our background research a paper was found that discussed hwo increasing native plant population around agricultural sites can increase pollinator population and lead to better harvest yields and overall healthier crops. 


We instend to use Oregon Bee Atlas Data and tequniques we have leared in class specfically looking at the lab 3  Hedgrows data to acomplish this task. A lot of what was done in Lab 3 will be greatly helpful as we are looking at what can be done to improve these hedgerows and increase native pollinator interactions in such areas. We discussed creating a tool that farmers can use to locate native plants that are associated with the area that they grow thier crops in to see the native plants that bees visit most often so they can be incoorporated into their growing areas. 

This is very important because it will help to increase the biodiversity and bring not only bees but other pollinators to an area and create a more ecologically mindful crop and farm in general. This helps to maintain the natural integretic of the land that has been converted for agricultural use.


- Dataset Id

The additional data that me and my partner will be using comes from a study that was done from June 2011- July 2021 at the H.J Andrews Experimental Forest. This study looked at plant-pollinator interactions across 18 Medows in the Willamette National Forest and 12 Medows in the Andrews Experimental Forest. There are 2 CSV files that were published with this study one that has plant pollinator interactions and a plant survey. The data was collected by individual observers as it was a long term observations study, but provided by the Andrew Forest website we do have the metrics that were used to count out the flowering plants, a taxonomic hierarchy that can be converted to a CSV file, we will have to narrow down a lot of the data in order to isolate just the bees as this study looked at many different pollinators. We also have a study site map that we can combine with OBA data that is from within the same areas as the Andrews Experimental Forest.  The study itself is called “Plant Pollinator Data At H.J Andrews Experimental Forest, 2011 to 2021”. This website also includes all of the metadata needed in order to read the columns and rows present. Included on the website is multiple publications that used data from this survey. 
https://andlter.forestry.oregonstate.edu/data/abstract.aspx?dbcode=SA026 

- Workflow

Plant Pollinator Interaction, OBA, Flowering Plant Surveys, Taxonomic Hierarchy

Tidying raw data:
	-Cleaning OBA Data to include only bee specimens from our target areas
	-Plant pollinator and flowering plants should be cleaned to match with the bee species found in the Oregon bee atlas to match them to plants and frequency of visits to add to the simulation
	- Tidy taxonomic hierarchy cleaned to match with our plants and bees from the OBA
	
	Testing can be done by filtering the data sets for each chosen forest to collect their unique bee and plant data. Estimating the density of bees in each site by counting occurrences of each repeat species can give a hypothetical starting population to be tested. Running a population simulation of bees in an environment with the variables of pollinated plants being added or removed to represent “management” and each unique location. Running these simulations can highlight which plants are most efficient at sustaining bee populations across several different sites by comparing population growth models against each other.
-A function for creating a population growth simulation would be modified to include “Fitness” for each plant based on an initial count of how many species visit a specific plant. 



- References
Andrews Forest Data Web Site. (2021). Andrews Forest. https://andlter.forestry.oregonstate.edu/data/abstract.aspx?dbcode=SA026
This dataset provides information about pollinators in different meadows and forests across Oregon. The flowering and plant-pollinator frequency data in this set will be used in simulation variables for our project.
MCIVER, J., THORP, R., & ERICKSON, K. (2009). Pollinators of the invasive plant, yellow starthistle (Centaurea solstitialis), in north-eastern Oregon, USA. Weed Biology and Management, 9(2), 137–145. https://doi.org/10.1111/j.1445-6664.2009.00331.x
	This study of an invasive plant in the Oregon area showed pollinator species interaction and abundance of pollinators in areas where the plants were introduced. Within the study it is found that this introduction led to an increase of visitations by several species and an increased density of population in each species. This supports our work by showing an introduced plant’s impact on a visiting population. 

Rao, S., & Stephen, W. P. (2010). Abundance and Diversity of Native Bumble Bees Associated with Agricultural Crops: The Willamette Valley Experience. Psyche: A Journal of Entomology, 2010, 1–9. https://doi.org/10.1155/2010/354072
	This study found that farming of foraging resources for wild bees in Oregon massively increased populations of wild bees and calls for the growth of pollen sources to increase and sustain bee populations. The call to action in this paper ties into our study looking to find ideal plants for this purpose. 	
Zitomer, R. A., Galbraith, S. M., Betts, M. G., Moldenke, A. R., Progar, R. A., & Rivers, J. W. (2023). Bee diversity decreases rapidly with time since harvest in intensively managed conifer forests. Ecological Applications, 33(5). https://doi.org/10.1002/eap.2855
	This study investigates bee populations in heavily harvested forests. It includes richness, floral diversity, and species richness of bee populations and shows marked declines under aging in heavily managed forests. This study provides background for the purpose of our work, as well as relevant data and support for our hypothesis.

- Partner Constitution

We me multiple times to discuss workflow plan together, Lucas wrote out the workflow and did the annotated bibliography. I wrote out the Literature review and dataset Identification. I also found our main data source outside of the OBA so that he can use it to build our simulation. 
